name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr: none

pool:
  name: 'self-agent-az-func'

resources:
  repositories:
    - repository: CICD
      type: github
      ref: main
      name: nhatthaiquang-agilityio/Terraform-CI-CD
      endpoint: nhatthaiquang-agilityio

variables:
  - name: AzureServiceConnection
    value: 'ExampleAzureServiceConnection'
  - name: AzureFunctionName
    value: 'durable-az-function'
stages:
  - stage: build
    displayName: Build
    pool:
      name: 'self-agent-az-func'
    jobs:
      - template: jobs/build-dotnet.yml@CICD
        parameters:
          BuildTargetPath: '**/DurableAzureFunction.csproj'
          DotNetVersion: '8.x'

  - stage: deploy
    displayName: Deploy Test
    dependsOn: build
    pool:
      name: 'self-agent-az-func'
    jobs:
      - deployment: deploy_azure_function
        environment: Test
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureFunctionApp@1
                inputs:
                  azureSubscription: '${{ variables.AzureServiceConnection }}'
                  appType: 'functionApp'
                  appName: '${{ variables.AzureFunctionName }}'
                  package: '$(Agent.BuildDirectory)\drop\*.zip'
