name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: CICD
      type: github
      ref: main
      name: nhatthaiquang-agilityio/Terraform-CI-CD
      endpoint: nhatthaiquang-agilityio

variables:
  - name: AzureServiceConnection
    value: 'ExampleAzureServiceConnection'
  - name: AzureFunctionName
    value: 'durable-az-function'
stages:
  - stage: build
    displayName: Build
    jobs:
      - template: jobs/build-dotnet.yml@CICD
        parameters:
          BuildTargetPath: '**/DurableAzureFunction.csproj'
          DotNetVersion: '8.x'

  - stage: deploy
    displayName: Deploy Test
    dependsOn: build
    jobs:
      - task: AzureFunctionApp@1
        inputs:
          azureSubscription: '${{ variables.AzureServiceConnection }}'
          appType: 'functionApp'
          appName: '${{ variables.AzureFunctionName }}'
          package: ''$(Agent.BuildDirectory)\drop\*.zip''